version: "3.7"
services:
  mysql:
    image: mysql:5
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: mercado.nota
      MYSQL_DATABASE: mismod
      MYSQL_USER: mismod
      MYSQL_PASSWORD: test.mismod
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  nginx_api:
    build:
      context: ./nginx_api
    restart: unless-stopped
    depends_on:
      - api
      - mysql
    volumes:
      - ./src/api/public:/var/www/api/public
      - ./nginx_api/logs:/var/log/nginx/
    ports:
      - 8600:80
    networks:
      - app-network
  api:
    build:
      context: ./src/api
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - type: bind
        source: ./src/api
        target: /var/www/api
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Docker Volumes
volumes:
  mysql_data: